-- ==========================================================
-- TASK 6 - SALES TREND ANALYSIS USING AGGREGATIONS
-- Database: MySQL
-- ==========================================================

USE online_sales;


-- ==========================================================
-- 1. View Complete Dataset
-- ==========================================================

SELECT *
FROM orders;

-- ==========================================================
-- 2. Monthly Revenue and Order Volume
-- ==========================================================

SELECT
    YEAR(order_date) AS Year,
    MONTH(order_date) AS Month,
    MONTHNAME(order_date) AS Month_Name,
    SUM(Total_Revenue) AS Total_Revenue,
    COUNT(DISTINCT Transaction_ID) AS Total_Orders
FROM orders
GROUP BY YEAR(order_date),
         MONTH(order_date),
         MONTHNAME(order_date)
ORDER BY Year, Month;

-- ==========================================================
-- 3. Monthly Revenue (Only)
-- ==========================================================

SELECT
    YEAR(order_date) AS Year,
    MONTH(order_date) AS Month,
    MONTHNAME(order_date) AS Month_Name,
    ROUND(SUM(Total_Revenue),2) AS Revenue
FROM orders
GROUP BY YEAR(order_date),
         MONTH(order_date),
         MONTHNAME(order_date)
ORDER BY Year, Month;

-- ==========================================================
-- 4. Monthly Order Volume
-- ==========================================================

SELECT
    YEAR(order_date) AS Year,
    MONTH(order_date) AS Month,
    MONTHNAME(order_date) AS Month_Name,
    COUNT(DISTINCT Transaction_ID) AS Orders
FROM orders
GROUP BY YEAR(order_date),
         MONTH(order_date),
         MONTHNAME(order_date)
ORDER BY Year, Month;

-- ==========================================================
-- 5. Average Order Value Per Month
-- ==========================================================

SELECT
    YEAR(order_date) AS Year,
    MONTH(order_date) AS Month,
    MONTHNAME(order_date) AS Month_Name,
    ROUND(AVG(Total_Revenue),2) AS Average_Order_Value
FROM orders
GROUP BY YEAR(order_date),
         MONTH(order_date),
         MONTHNAME(order_date)
ORDER BY Year, Month;

-- ==========================================================
-- 6. Maximum Sale Per Month
-- ==========================================================

SELECT
    YEAR(order_date) AS Year,
    MONTH(order_date) AS Month,
    MONTHNAME(order_date) AS Month_Name,
    MAX(Total_Revenue) AS Highest_Sale
FROM orders
GROUP BY YEAR(order_date),
         MONTH(order_date),
         MONTHNAME(order_date)
ORDER BY Year, Month;

-- ==========================================================
-- 7. Minimum Sale Per Month
-- ==========================================================

SELECT
    YEAR(order_date) AS Year,
    MONTH(order_date) AS Month,
    MONTHNAME(order_date) AS Month_Name,
    MIN(Total_Revenue) AS Lowest_Sale
FROM orders
GROUP BY YEAR(order_date),
         MONTH(order_date),
         MONTHNAME(order_date)
ORDER BY Year, Month;

-- ==========================================================
-- 8. Total Products Sold Per Month
-- ==========================================================

SELECT
    YEAR(order_date) AS Year,
    MONTH(order_date) AS Month,
    MONTHNAME(order_date) AS Month_Name,
    COUNT(Product_Name) AS Products_Sold
FROM orders
GROUP BY YEAR(order_date),
         MONTH(order_date),
         MONTHNAME(order_date)
ORDER BY Year, Month;

-- ==========================================================
-- 9. Top 3 Months By Revenue
-- ==========================================================

SELECT
    YEAR(order_date) AS Year,
    MONTHNAME(order_date) AS Month_Name,
    ROUND(SUM(Total_Revenue),2) AS Revenue
FROM orders
GROUP BY YEAR(order_date),
         MONTH(order_date),
         MONTHNAME(order_date)
ORDER BY Revenue DESC
LIMIT 3;

-- ==========================================================
-- 10. Top 5 Months By Number of Orders
-- ==========================================================

SELECT
    YEAR(order_date) AS Year,
    MONTHNAME(order_date) AS Month_Name,
    COUNT(DISTINCT Transaction_ID) AS Orders
FROM orders
GROUP BY YEAR(order_date),
         MONTH(order_date),
         MONTHNAME(order_date)
ORDER BY Orders DESC
LIMIT 5;

-- ==========================================================
-- 11. Revenue for a Particular Year (Example: 2024)
-- ==========================================================

SELECT
    MONTH(order_date) AS Month,
    MONTHNAME(order_date) AS Month_Name,
    ROUND(SUM(Total_Revenue),2) AS Revenue
FROM orders
WHERE YEAR(order_date)=2024
GROUP BY MONTH(order_date),
         MONTHNAME(order_date)
ORDER BY Month;

-- ==========================================================
-- 12. Revenue Generated By Each Product
-- ==========================================================

SELECT
    product_name,
    ROUND(SUM(Total_Revenue),2) AS Revenue
FROM orders
GROUP BY Product_Name
ORDER BY Revenue DESC;

-- ==========================================================
-- 13. Number of Orders By Product Category
-- ==========================================================

SELECT
    Product_Category,
    COUNT(DISTINCT Transaction_ID) AS Orders
FROM orders
GROUP BY Product_Category
ORDER BY Orders DESC;

-- ==========================================================
-- 14. Overall Sales Summary
-- ==========================================================

SELECT
    ROUND(SUM(Total_Revenue),2) AS Total_Revenue,
    ROUND(AVG(Total_Revenue),2) AS Average_Order_Value,
    MAX(Total_Revenue) AS Highest_Order,
    MIN(Total_Revenue) AS Lowest_Order,
    COUNT(DISTINCT Transaction_ID) AS Total_Orders,
    COUNT(Product_Name) AS Total_Items
FROM orders;

-- ==========================================================
-- 15. Check for NULL Values
-- ==========================================================

SELECT
    COUNT(*) AS Total_Rows,
    COUNT(order_date) AS Non_Null_Dates,
    COUNT(Total_Revenue) AS Non_Null_Amount,
    COUNT(Product_Name) AS Non_Null_ProductName
FROM orders;

-- ==========================================================
-- 16. Monthly Revenue with Running Total
-- ==========================================================

WITH monthly_sales AS
(
SELECT
    YEAR(order_date) AS `Year`,
    MONTH(order_date) AS `Month`,
    ROUND(SUM(Total_Revenue),2) AS Revenue
FROM orders
GROUP BY YEAR(order_date), MONTH(order_date)
)

SELECT *,
SUM(Revenue) OVER(ORDER BY Year, Month) AS Running_Total
FROM monthly_sales;

-- =========================================================
-- 17. Revenue by Product Category
-- =========================================================

SELECT Product_Category ,
			 ROUND(SUM(Total_Revenue) , 2)Revenue ,
       COUNT(Transaction_ID) Sales
FROM orders
GROUP BY Product_Category
ORDER BY Revenue

-- ==========================================================
-- END OF TASK
-- ==========================================================